name: sign_up_skeleton

packages:
  - app
  - packages/core
  - packages/data
  - packages/domain
  - packages/presentation

scripts:
  ###############################################
  ##              BUILD COMMANDS               ##
  ###############################################
  get:
    run: fvm flutter pub get
    exec:
      concurrency: 6
    description: Install all dependencies

  build:clean:all:
    run: |
      fvm flutter clean && \
      fvm flutter pub get
    description: Clean Flutter package and install dependencies for all packages

  build:codegen:build:
    run: fvm flutter pub run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
      orderDependents: true
    packageFilters:
      dependsOn: "build_runner"
    description: Run code generation using build_runner in a specific package

  build:codegen:build:all:
    run: melos run build:codegen:build --no-select
    description: Run code generation using build_runner for all packages in the project

  build:codegen:watch:
    run: dart run build_runner watch --delete-conflicting-outputs
    exec:
      concurrency: 1
      orderDependents: true
    packageFilters:
      dependsOn: "build_runner"
    description: Run code generation using build_runner in a specific package, and watch any changes in this package

  build:codegen:watch:all:
    run: melos run build:codegen:watch --no-select
    description: Run code generation using build_runner in a all packages, and watch any changes

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0 <4.0.0"
