name: presentation
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.4.1

dependencies:
  flutter:
    sdk: flutter

  # Local dependencies:
  domain:
    path: ../domain
  core:
    path: ../core

  get_it: ^8.0.2
  injectable: ^2.5.0
  go_router: ^14.4.0
  flutter_svg: ^2.0.11
  google_fonts: ^6.2.1
  reactive_forms: ^17.0.1
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  lints: ^3.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/
    - assets/fonts/