name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

  # Local dependencies
  data:
    path: ../data
  core:
    path: ../core

  get_it: ^8.0.2
  injectable: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  lints: ^3.0.0
  test: ^1.24.0
