name: domain
description: Domain layer of the application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  # Local dependencies
  data:
    path: ../data
  core:
    path: ../core

  get_it: ^8.0.2
  injectable: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  flutter_lints: ^5.0.0
